name: Call Koyfin API Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API with timestamp and response code
        run: |
          echo "=== API Call Started at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
          
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST "https://koyfinapi-qa.sdlc.ai/v1/views/kairos-scheduler-bot/daily-summary/collapsed" \
            -H "Content-Type: application/json" \
            -d '{"type":"by_value","enable_column":false}')
          
          echo "Response Code: $response"
          echo -n "Response Preview: "
          head -c 10 response.json
          echo ""  # newline
